"""criar_tabelas_aeroporto

Revision ID: e3d675921fd2
Revises: 096b6034262d
Create Date: 2026-07-24 09:06:22.841502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d675921fd2'
down_revision: Union[str, Sequence[str], None] = '096b6034262d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefixo', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('companhia', sa.String(length=60), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacidade > 0', name='ck_aeronave_capacidade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefixo')
    )
    op.create_table('passageiros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_index(op.f('ix_passageiros_nome'), 'passageiros', ['nome'], unique=False)
    op.create_table('terminais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.Enum('NACIONAL', 'INTERNACIONAL', name='tipo_terminal'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('GATE', 'REMOTA', name='tipo_vaga'), nullable=False),
    sa.Column('status', sa.Enum('LIVRE', 'OCUPADA', 'MANUTENCAO', name='status_vaga'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_vagas_status'), 'vagas', ['status'], unique=False)
    op.create_index(op.f('ix_vagas_terminal_id'), 'vagas', ['terminal_id'], unique=False)
    op.create_table('voos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=3), nullable=False),
    sa.Column('destino', sa.String(length=3), nullable=False),
    sa.Column('partida_prevista', sa.DateTime(), nullable=False),
    sa.Column('chegada_prevista', sa.DateTime(), nullable=False),
    sa.Column('partida_real', sa.DateTime(), nullable=True),
    sa.Column('chegada_real', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NO_HORARIO', 'ATRASADO', 'EMBARQUE', 'FINALIZADO', 'CANCELADO', name='status_voo'), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_voos_aeronave_id'), 'voos', ['aeronave_id'], unique=False)
    op.create_index(op.f('ix_voos_chegada_prevista'), 'voos', ['chegada_prevista'], unique=False)
    op.create_index(op.f('ix_voos_destino'), 'voos', ['destino'], unique=False)
    op.create_index(op.f('ix_voos_origem'), 'voos', ['origem'], unique=False)
    op.create_index(op.f('ix_voos_partida_prevista'), 'voos', ['partida_prevista'], unique=False)
    op.create_index(op.f('ix_voos_status'), 'voos', ['status'], unique=False)
    op.create_index(op.f('ix_voos_terminal_id'), 'voos', ['terminal_id'], unique=False)
    op.create_table('alocacoes_vaga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voo_id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('finalidade', sa.Enum('DESEMBARQUE', 'EMBARQUE', 'ABASTECIMENTO', 'PERNOITE', name='finalidade_alocacao'), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voo_id'], ['voos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alocacoes_vaga_ativa'), 'alocacoes_vaga', ['ativa'], unique=False)
    op.create_index(op.f('ix_alocacoes_vaga_vaga_id'), 'alocacoes_vaga', ['vaga_id'], unique=False)
    op.create_index(op.f('ix_alocacoes_vaga_voo_id'), 'alocacoes_vaga', ['voo_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passageiro_id', sa.Integer(), nullable=False),
    sa.Column('voo_id', sa.Integer(), nullable=False),
    sa.Column('assento', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CHECK_IN_FEITO', 'EMBARCADA', 'NO_SHOW', 'REALOCADA', 'CANCELADA', name='status_reserva'), nullable=False),
    sa.Column('check_in_em', sa.DateTime(), nullable=True),
    sa.Column('reserva_origem_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passageiro_id'], ['passageiros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_origem_id'], ['reservas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voo_id'], ['voos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passageiro_id', 'voo_id', name='uq_reserva_passageiro_voo'),
    sa.UniqueConstraint('voo_id', 'assento', name='uq_reserva_voo_assento')
    )
    op.create_index(op.f('ix_reservas_passageiro_id'), 'reservas', ['passageiro_id'], unique=False)
    op.create_index(op.f('ix_reservas_reserva_origem_id'), 'reservas', ['reserva_origem_id'], unique=False)
    op.create_index(op.f('ix_reservas_status'), 'reservas', ['status'], unique=False)
    op.create_index(op.f('ix_reservas_voo_id'), 'reservas', ['voo_id'], unique=False)
    op.create_table('bagagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etiqueta', sa.String(length=20), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DESPACHADA', 'EM_TRIAGEM', 'CARREGADA', 'EXTRAVIADA', 'ENTREGUE', name='status_bagagem'), nullable=False),
    sa.Column('local_atual', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etiqueta')
    )
    op.create_index(op.f('ix_bagagens_reserva_id'), 'bagagens', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_bagagens_status'), 'bagagens', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bagagens_status'), table_name='bagagens')
    op.drop_index(op.f('ix_bagagens_reserva_id'), table_name='bagagens')
    op.drop_table('bagagens')
    op.drop_index(op.f('ix_reservas_voo_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_status'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_reserva_origem_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_passageiro_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_alocacoes_vaga_voo_id'), table_name='alocacoes_vaga')
    op.drop_index(op.f('ix_alocacoes_vaga_vaga_id'), table_name='alocacoes_vaga')
    op.drop_index(op.f('ix_alocacoes_vaga_ativa'), table_name='alocacoes_vaga')
    op.drop_table('alocacoes_vaga')
    op.drop_index(op.f('ix_voos_terminal_id'), table_name='voos')
    op.drop_index(op.f('ix_voos_status'), table_name='voos')
    op.drop_index(op.f('ix_voos_partida_prevista'), table_name='voos')
    op.drop_index(op.f('ix_voos_origem'), table_name='voos')
    op.drop_index(op.f('ix_voos_destino'), table_name='voos')
    op.drop_index(op.f('ix_voos_chegada_prevista'), table_name='voos')
    op.drop_index(op.f('ix_voos_aeronave_id'), table_name='voos')
    op.drop_table('voos')
    op.drop_index(op.f('ix_vagas_terminal_id'), table_name='vagas')
    op.drop_index(op.f('ix_vagas_status'), table_name='vagas')
    op.drop_table('vagas')
    op.drop_table('terminais')
    op.drop_index(op.f('ix_passageiros_nome'), table_name='passageiros')
    op.drop_table('passageiros')
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
